### ISSUE TITLE
support Ed25519 to Curve25519 keys conversion

### ISSUE THREAD

**Issue by leslie-wang** [kevinburke/nacl#5]
This should be very useful, such as https://download.libsodium.org/doc/advanced/ed25519-curve25519.html

golang has such plan, but seems like no progress. https://github.com/golang/go/issues/20504

**Comment by kevinburke** [comment]
To be honest I'm not sure I feel comfortable implementing this on my own...

What should the API look like you think?

**Comment by kevinburke** [comment]
Also worried that the API's currently present in this package are present in nacl.cr.yp.to, but the proposed API would not be, as far as I can tell - it's in libsodium but not here.
